name: Check Azure Login

on:
  workflow_dispatch:

jobs:
  check_login:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Download Azure CLI Installer
        run: |
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\azure-cli.msi
     
      - name: Install Azure CLI
        run: |
          Start-Process msiexec.exe -Wait -ArgumentList '/I azure-cli.msi /quiet /norestart'
      
      - name: Check Azure CLI Version
        run: az --version
     
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: List Azure Subscriptions
        run: az account list
      - name: Create Azure Service Bus Namespace
        shell: cmd
        run: az servicebus namespace create --name 'Test18' --resource-group 'testgit' --location 'westus'
